name: e2e tests

on: [push]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          build: SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} npm run build
          start: npm start
          wait-on: "http://localhost:3000"
